### ISSUE TITLE
Audio kept buffering, missing play/pause keybind in config

### ISSUE THREAD

**Issue by DaGamerFiles** [KabanFriends/CraftGR#18]
I'm playing on Forge 1.20.1 and noticed that the audio buffered too much recently, I have no issues in web browser/normal media player playback. The keybind for Play/Pause are also missing.

Here's the log:
```
java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readFully(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:243)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1509)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1480)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1066)
	at MC-BOOTSTRAP/org.apache.httpcomponents.httpcore@4.4.15/org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at MC-BOOTSTRAP/org.apache.httpcomponents.httpcore@4.4.15/org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:197)
	at MC-BOOTSTRAP/org.apache.httpcomponents.httpcore@4.4.15/org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:188)
	at MC-BOOTSTRAP/org.apache.httpcomponents.httpclient@4.5.13/org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:291)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:347)
	at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:119)
	at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:197)
	at TRANSFORMER/craftgr@1.5.1/javazoom.jl.decoder.Bitstream.readFully(Bitstream.java:605)
	at TRANSFORMER/craftgr@1.5.1/javazoom.jl.decoder.Bitstream.read_frame_data(Bitstream.java:488)
	at TRANSFORMER/craftgr@1.5.1/javazoom.jl.decoder.Header.read_header(Header.java:178)
	at TRANSFORMER/craftgr@1.5.1/javazoom.jl.decoder.Bitstream.nextFrame(Bitstream.java:328)
	at TRANSFORMER/craftgr@1.5.1/javazoom.jl.decoder.Bitstream.readNextFrame(Bitstream.java:315)
	at TRANSFORMER/craftgr@1.5.1/javazoom.jl.decoder.Bitstream.readFrame(Bitstream.java:269)
	at TRANSFORMER/craftgr@1.5.1/forge.io.github.kabanfriends.craftgr.audio.AudioPlayer.decodeFrame(AudioPlayer.java:88)
	at TRANSFORMER/craftgr@1.5.1/forge.io.github.kabanfriends.craftgr.audio.AudioPlayer.play(AudioPlayer.java:60)
	at TRANSFORMER/craftgr@1.5.1/forge.io.github.kabanfriends.craftgr.handler.AudioPlayerHandler.startPlayback(AudioPlayerHandler.java:30)
	at TRANSFORMER/craftgr@1.5.1/forge.io.github.kabanfriends.craftgr.util.AudioPlayerUtil.lambda$startPlaybackAsync$0(AudioPlayerUtil.java:25)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
[01:01:22] [pool-7-thread-5/ERROR] [fo.io.gi.ka.cr.CraftGR/]: [CraftGR] Error during audio playback! Restarting in 5 seconds...
[01:01:25] [Sound engine/ERROR] [mojang/OpenAlUtil]: Allocate new source: Invalid operation.
[01:01:27] [pool-7-thread-6/INFO] [fo.io.gi.ka.cr.CraftGR/]: [CraftGR] Connecting to the audio stream...
[01:01:29] [pool-7-thread-6/INFO] [fo.io.gi.ka.cr.CraftGR/]: [CraftGR] Audio player is ready!
```

**Comment by KabanFriends** [comment]
I added configurable time out duration in update 1.8.0. And the keybind is fixed there too.
